=== Mskina/LMSXI/LMSXI02/Tarea02.1/pedido.dtd
<!-- Aquí declaro la entidad de dirección junto con los elementos que la conforman -->
<!ENTITY % direccion "tipo_via, nombre_via, numero_via?, bloque?, planta?, puerta?, poblacion, provincia, pais?">
<!ELEMENT tipo_via (#PCDATA)>
<!ELEMENT nombre_via (#PCDATA)>
<!ELEMENT numero_via (#PCDATA)>
<!ELEMENT bloque (#PCDATA)>
<!ELEMENT planta (#PCDATA)>
<!ELEMENT puerta (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!-- Aquí declaro la entidad de datos personales junto con los elementos que la conforman -->
<!ENTITY % personal "(nombre, apellidos)|(apellidos, nombre)"> <!-- Está declarado de esa forma porque se indica que pueden aparecer como nombre+apellidos o apellidos+nombre -->
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!-- pedido -->
<!ELEMENT pedido (cliente, producto+, datos_envio, total)>
<!ATTLIST pedido num ID #REQUIRED>
<!ATTLIST pedido fecha_hora NMTOKEN #REQUIRED>
<!-- cliente -->
<!ELEMENT cliente ((%personal;), (dni|nie), direccion_facturacion)>
<!ATTLIST cliente id ID #REQUIRED>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT nie (#PCDATA)>
<!ELEMENT direccion_facturacion (%direccion;)>
<!-- producto -->
<!ELEMENT producto (#PCDATA|precio|unidades)*>
<!ATTLIST producto id ID #REQUIRED>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT unidades (#PCDATA)>
<!-- datos_envio -->
<!ELEMENT datos_envio (destinatario, direccion_envio)?>
<!ATTLIST datos_envio tipo (estándar|urgente) "estándar">
<!ATTLIST datos_envio cliente IDREF #IMPLIED>
<!ELEMENT destinatario (%personal;)>
<!ELEMENT direccion_envio (%direccion;)>
<!-- total -->
<!ELEMENT total (#PCDATA)>
<!ATTLIST total descuento CDATA #IMPLIED>

=== Mskina/LMSXI/LMSXI02/Tarea02.1/tarea02-1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE pedido SYSTEM "pedido.dtd">
<pedido num="P-0001" fecha_hora="2021-10-01T17:54:12">
    <cliente id="C-999">
        <nombre>Rita</nombre>
        <apellidos>Díaz Zapata</apellidos>
        <dni>12345678-B</dni>
        <direccion_facturacion>
            <tipo_via>Avenida</tipo_via>
            <nombre_via>de Madrid</nombre_via>
            <numero_via>23</numero_via>
            <bloque></bloque>
            <planta>4º</planta>
            <puerta></puerta>
            <poblacion>Vigo</poblacion>
            <provincia>Pontevedra</provincia>
        </direccion_facturacion>
    </cliente>
    <producto id="P-aaa">
        Set de regalo especial cumpleaños
        <precio>185</precio>
        <unidades>1</unidades>
    </producto>
    <producto id="P-bbb1">
        Estuche Champagnes Moët &amp; Chandon Brut Impérial Estuche 3 botellas
        <precio>119,54</precio>
        <unidades>1</unidades>
    </producto>
    <datos_envio tipo="urgente">
        <destinatario>
            <apellidos>López Reyes</apellidos>
            <nombre>Ana</nombre>
        </destinatario>
        <direccion_envio>
            <tipo_via>Rue</tipo_via>
            <nombre_via>Saint Jacques</nombre_via>
            <numero_via>nº1</numero_via>
            <bloque></bloque>
            <planta>5º</planta>
            <puerta>B</puerta>
            <poblacion>Paris</poblacion>
            <provincia>Paris</provincia>
            <pais>Francia</pais>
        </direccion_envio>
    </datos_envio>
    <total descuento="10">274,09</total>
</pedido>
