=== Mskina/LMSXI/LMSXI02/DTD/2.1.2-DTD-ENTITIES-Ejemplos/2.1.2.6.1-direccion.dtd
<!ELEMENT carta (emisor, receptor)>
<!ENTITY % datos_direccion "tipo_via, nombre_via, numero?, bloque?, piso, letra">
<!-- La entidad datos_personales hace referencia a su vez a la entidad datos_direccion -->
<!ENTITY % datos_personales "nombre, apellidos, %datos_direccion;">
<!ELEMENT emisor (%datos_personales;)>
<!ELEMENT receptor (%datos_personales;)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>

<!ELEMENT tipo_via (#PCDATA)>
<!ELEMENT nombre_via (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT bloque (#PCDATA)>
<!ELEMENT piso (#PCDATA)>
<!ELEMENT letra (#PCDATA)>

=== Mskina/LMSXI/LMSXI02/DTD/2.1.2-DTD-ENTITIES-Ejemplos/2.1.2.6-entidades-parametro-el.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE carta SYSTEM "2.1.2.6.1-direccion.dtd">
<carta>
    <emisor>
        <nombre>Ana </nombre>
        <apellidos>LÃ³pez Mar</apellidos>
        <tipo_via>Avenida</tipo_via>
        <nombre_via>de Vigo</nombre_via>
        <numero>2</numero>
        <piso>1</piso>
        <letra>D</letra>
    </emisor>
    <receptor>
        <nombre>Beatriz </nombre>
        <apellidos>Luz Serrano</apellidos>
        <tipo_via>Calle</tipo_via>
        <nombre_via>San Juan</nombre_via>
        <piso>Bajo</piso>
        <letra>E</letra>
    </receptor>
</carta>
